name: fastapi-lungdiseases
services:
  fastapi:
    public: true
    image: okteto.dev/fastapi-lungdiseases:latest
    build: .
    replicas: 1
    ports:
      - 8080

    resources:
      cpu: 1000m
      memory: 1280Mi



